// Artículos originales del sitio, adaptados de la columna "Papeles en Regla" que
// el Lic. Daguer Hernández escribe para Confidencial (confidencial.digital). El
// contenido legal (artículos de ley, decretos, plazos, montos) se mantiene fiel
// a la columna original — solo se reestructura/expande la redacción para el sitio.
// Los ids 1/2/3 coinciden con los de PapelesRegla.jsx (mismo orden de artículos).

export const blogArticles = [
  {
    id: 1,
    slug: { es: 'permanencia-legal-costa-rica-requisitos-multas', en: 'legal-stay-costa-rica-requirements-fines' },
    image: 'https://confidencial.digital/wp-content/uploads/2025/03/Aeropuerto-Liberia-Costa-Rica.jpg',
    source: {
      url: 'https://confidencial.digital/migrantes/migrantes-noticias/papeles-en-regla/permanencia-legal-en-costa-rica-guia-completa-para-turistas-o-extranjeros/',
      dateEs: '17 de marzo de 2025',
      dateEn: 'March 17, 2025',
    },
    es: {
      title: 'Permanencia legal en Costa Rica: requisitos, plazos y multas para turistas y extranjeros',
      dek: 'Guía completa sobre los requisitos, el tiempo permitido y las multas por permanencia irregular en Costa Rica, incluyendo las excepciones que contempla la ley.',
      metaDescription: 'Requisitos, plazos y multas para la permanencia legal en Costa Rica: cuánto tiempo puede quedarse un turista, cómo cambiar de categoría migratoria y qué excepciones existen.',
      imageAlt: 'Puesto migratorio en aeropuerto de Costa Rica',
      body: [
        { type: 'p', text: 'La permanencia legal es el principio por el cual las personas migrantes, turistas o extranjeros en general mantienen una condición migratoria regular dentro de Costa Rica, lo que les permite acceder a una categoría migratoria específica. Este concepto está regulado en el artículo 66 de la Ley General de Migración y Extranjería (Ley 8764).' },
        { type: 'h2', text: '¿Cuáles son los requisitos para la permanencia legal en Costa Rica?' },
        { type: 'p', text: 'Para permanecer legalmente en Costa Rica, una persona debe haber ingresado al país cumpliendo los siguientes requisitos:' },
        { type: 'ul', items: [
          'Pasaporte vigente (excepto ciudadanos venezolanos, quienes pueden ingresar con pasaporte vencido).',
          'Cumplimiento de las condiciones de visa, si corresponde.',
          'Entrada por un puesto fronterizo autorizado.',
        ] },
        { type: 'h2', text: '¿Cuánto tiempo puede permanecer un extranjero en Costa Rica como turista?' },
        { type: 'p', text: 'El tiempo de permanencia legal como turista lo determina el oficial de migración en el punto de ingreso (aéreo, terrestre o marítimo), y por lo general no supera los 90 días. Durante ese período, la persona puede solicitar una categoría migratoria ante la Dirección General de Migración y Extranjería (DGME).' },
        { type: 'h2', text: '¿Qué hacer si necesito quedarme más tiempo del autorizado?' },
        { type: 'p', text: 'Según el artículo 89 de la Ley 8764, los turistas que deseen cambiar su estatus migratorio deben pagar una tarifa de 200 dólares. Una vez presentado el trámite, la permanencia legal se prorroga automáticamente mientras la solicitud esté en proceso, aunque esto no otorga derecho a salir y reingresar al país sin cumplir nuevamente con los requisitos migratorios. Si la solicitud es aprobada, la persona puede ingresar con la resolución favorable dentro de un período de 90 días para completar su documentación.' },
        { type: 'h2', text: '¿Cuál es la multa por permanencia irregular en Costa Rica?' },
        { type: 'p', text: 'Si una persona permanece en el país más allá del tiempo autorizado y no puede salir para regularizar su estatus, puede pagar una multa conforme al artículo 91 de la Ley 8764. El costo es de 100 dólares por cada mes de permanencia vencida, y el pago debe realizarse en la cuenta del Banco de Costa Rica:' },
        { type: 'ul', items: ['IBAN: CR82015201001008005117', 'IBAN: CR95015201001008005465'] },
        { type: 'p', text: 'Por ejemplo, si una persona permaneció en Costa Rica seis meses después de la fecha autorizada, deberá pagar 300 dólares antes de presentar su trámite migratorio.' },
        { type: 'h2', text: '¿Qué excepciones existen para no actualizar la permanencia legal?' },
        { type: 'p', text: 'Existen casos en los que no se requiere actualizar la permanencia legal:' },
        { type: 'ul', items: [
          'Padres o madres de menores costarricenses: deben demostrar, mediante declaración jurada, que salir del país afectaría la patria potestad (artículo 58 del Reglamento de Extranjería, Decreto Ejecutivo 37112-GOB).',
          'Menores de edad: conforme a los artículos 56 del Reglamento de Extranjería y 69 de la Ley 8764.',
          'Solicitantes por razones humanitarias: según los mismos artículos mencionados.',
          'Personas migrantes con condenas en Costa Rica: se les concede una autorización provisional de permanencia mientras cumplen su sentencia (artículo 72 de la Ley 8764).',
        ] },
        { type: 'h2', text: '¿Por qué importa mantener la permanencia legal vigente?' },
        { type: 'p', text: 'Para presentar cualquier trámite migratorio es fundamental que la persona se encuentre en permanencia legal vigente. De lo contrario, el trámite puede ser rechazado por inadmisibilidad, conforme al artículo 69 de la Ley 8764.' },
        { type: 'p', text: 'Cada caso migratorio tiene particularidades que conviene revisar antes de tomar una decisión. Si tu permanencia está por vencer o ya está vencida, agenda una consulta para evaluar tu situación específica.' },
      ],
    },
    en: {
      title: 'Legal Stay in Costa Rica: Requirements, Deadlines, and Fines for Tourists and Foreigners',
      dek: 'A complete guide to the requirements, allowed length of stay, and fines for irregular stay in Costa Rica, including the exceptions the law provides for.',
      metaDescription: 'Requirements, deadlines, and fines for legal stay in Costa Rica: how long a tourist can stay, how to change immigration status, and what exceptions exist.',
      imageAlt: 'Immigration checkpoint at a Costa Rica airport',
      body: [
        { type: 'p', text: 'Legal stay is the principle by which migrants, tourists, or foreign nationals in general maintain a regular immigration status within Costa Rica, which allows them to access a specific immigration category. This concept is regulated under article 66 of the General Immigration Law (Law 8764).' },
        { type: 'h2', text: 'What are the requirements for legal stay in Costa Rica?' },
        { type: 'p', text: 'To stay legally in Costa Rica, a person must have entered the country meeting the following requirements:' },
        { type: 'ul', items: [
          'A valid passport (except for Venezuelan citizens, who may enter with an expired passport).',
          'Compliance with visa conditions, if applicable.',
          'Entry through an authorized border checkpoint.',
        ] },
        { type: 'h2', text: 'How long can a foreigner stay in Costa Rica as a tourist?' },
        { type: 'p', text: 'The length of legal stay as a tourist is determined by the immigration officer at the point of entry (air, land, or sea), and generally does not exceed 90 days. During that period, the person can apply for an immigration category before the General Directorate of Migration and Immigration (DGME).' },
        { type: 'h2', text: 'What should I do if I need to stay longer than authorized?' },
        { type: 'p', text: 'Under article 89 of Law 8764, tourists who wish to change their immigration status must pay a fee of $200. Once the application is filed, the legal stay is automatically extended while the application is in process — although this does not grant the right to leave and re-enter the country without meeting the immigration requirements again. If the application is approved, the person may enter with the favorable resolution within a 90-day period to complete their documentation.' },
        { type: 'h2', text: 'What is the fine for irregular stay in Costa Rica?' },
        { type: 'p', text: 'If a person remains in the country beyond the authorized time and cannot leave to regularize their status, they may pay a fine under article 91 of Law 8764. The cost is $100 for each month of overstay, payable to the Bank of Costa Rica account:' },
        { type: 'ul', items: ['IBAN: CR82015201001008005117', 'IBAN: CR95015201001008005465'] },
        { type: 'p', text: 'For example, if a person stayed in Costa Rica for six months past the authorized date, they would need to pay $300 before filing their immigration application.' },
        { type: 'h2', text: 'What exceptions exist for not renewing legal stay?' },
        { type: 'p', text: 'There are cases in which legal stay does not need to be renewed:' },
        { type: 'ul', items: [
          'Parents of Costa Rican minors: must demonstrate, through a sworn statement, that leaving the country would affect parental authority (article 58 of the Immigration Regulations, Executive Decree 37112-GOB).',
          'Minors: under articles 56 of the Immigration Regulations and 69 of Law 8764.',
          'Applicants for humanitarian reasons: under the same articles mentioned above.',
          'Migrants serving a sentence in Costa Rica: they are granted a provisional stay authorization while serving their sentence (article 72 of Law 8764).',
        ] },
        { type: 'h2', text: 'Why does keeping legal stay current matter?' },
        { type: 'p', text: 'To file any immigration application, it is essential that the person be in current legal stay. Otherwise, the application may be rejected as inadmissible, under article 69 of Law 8764.' },
        { type: 'p', text: 'Every immigration case has particularities worth reviewing before making a decision. If your legal stay is about to expire or has already expired, schedule a consultation to review your specific situation.' },
      ],
    },
  },
  {
    id: 2,
    slug: { es: 'dimex-vencido-como-regresar-renovar-residencia-costa-rica', en: 'expired-dimex-how-to-return-renew-residency-costa-rica' },
    image: 'https://confidencial.digital/wp-content/uploads/2025/02/aeropuerto-juan-santamaria.jpg',
    source: {
      url: 'https://confidencial.digital/migrantes/migrantes-noticias/papeles-en-regla/como-regresar-a-costa-rica-tras-migrar-a-estados-unidos/',
      dateEs: '25 de febrero de 2025',
      dateEn: 'February 25, 2025',
    },
    es: {
      title: 'DIMEX vencido: cómo regresar a Costa Rica y renovar tu residencia o refugio',
      dek: 'Guía para personas que migraron a Estados Unidos u otro país y necesitan regresar a Costa Rica con su documento migratorio (DIMEX) vencido.',
      metaDescription: 'Cómo renovar el DIMEX vencido y regresar a Costa Rica tras migrar a Estados Unidos: qué categorías migratorias se pueden renovar, cuáles no, y qué hacer en cada caso.',
      imageAlt: 'Aeropuerto Juan Santamaría en Costa Rica',
      body: [
        { type: 'p', text: 'Esta guía está dirigida a personas migrantes que salieron de Costa Rica hacia Estados Unidos —por múltiples razones o por su condición de irregularidad migratoria— y que ahora deben o desean regresar al país, así como a quienes se quedaron en Costa Rica sin renovar los documentos que comprueban su categoría migratoria.' },
        { type: 'p', text: 'La mayoría de las personas costarricenses no opta por la emigración: hay aproximadamente 180 000 costarricenses en Estados Unidos, mientras que unos 230 000 estadounidenses se encuentran en Costa Rica, la mayoría sin documentos migratorios para estar en el país. Sin embargo, algunas personas nacionales de Nicaragua, Cuba, Venezuela, Haití u otros países sí han migrado a Estados Unidos u otros destinos después de haber obtenido documentos en Costa Rica, como residencias permanentes, temporales o categorías especiales.' },
        { type: 'h2', text: '¿Qué categorías migratorias se pueden renovar en Costa Rica?' },
        { type: 'p', text: 'Dos categorías se pueden renovar incluso después de vencidas: la Residencia Permanente y la Categoría de Refugio Aprobado (con resolución aprobatoria). Ambas se pueden renovar aunque hayan pasado los tres meses de vencimiento.' },
        { type: 'p', text: 'A las personas que tengan menos de 10 años con el documento vencido de Residencia Permanente o de Refugio Aprobado se les puede renovar mediante una cita al 1311, explicando las razones por las cuales no hizo la renovación, por medio de una nota autenticada por un abogado. Si la persona salió del país, debe aportar el documento de antecedentes penales o récord de policía apostillado del país del cual está regresando.' },
        { type: 'h2', text: '¿Cómo regresar a Costa Rica si el DIMEX está vencido?' },
        { type: 'p', text: 'Lo recomendable es solicitar un Certificado de Estatus Migratorio a la Dirección General de Migración y Extranjería, a través del correo certificacionstatus@migracion.go.cr. Con esa certificación y el DIMEX vencido, se puede demostrar el derecho y la posibilidad de entrar al país ante la aerolínea, para el abordaje, y posteriormente completar la renovación del DIMEX en Costa Rica.' },
        { type: 'h2', text: '¿Qué hago si migré con parole humanitario a Estados Unidos?' },
        { type: 'p', text: 'Un ejemplo frecuente: una persona nicaragüense con Residencia Permanente en Costa Rica, vencida desde hace ocho años, salió de forma legal hacia Estados Unidos mediante el Parole Humanitario. Antes de regresar a Costa Rica, esta persona debe solicitar el Antecedente Penal Federal, apostillado en Estados Unidos, y gestionar su boleto de avión considerando siempre la compra del vuelo con la aceptación de su DIMEX vencido, o bien ubicar una certificación de estatus para asegurar un regreso ordenado. Si han pasado más de 10 años sin renovación, además de los antecedentes penales apostillados, debe pedirse una autorización formal para que se determine si procede o no la renovación del DIMEX.' },
        { type: 'h2', text: '¿Qué categorías migratorias no se pueden renovar?' },
        { type: 'p', text: 'No se pueden renovar las Residencias Temporales con más de tres meses de vencidas, las Categorías Especiales (cualquiera) con más de tres meses vencidas, y las Estancias con más de tres meses vencidas. Es importante revisar la leyenda que aparece en el DIMEX azul o verde: Residencia Temporal, Categoría Especial Libre Condición (con excepción del Refugio Aprobado), Categoría Especial Condición Restringida, Subcategoría de Nómada Digital o Estancia. Si se dejaron vencer por más de tres meses, se consideran caducas, sin posibilidad de renovación.' },
        { type: 'h2', text: '¿Qué hacer si mi categoría no puede renovarse?' },
        { type: 'p', text: 'En ese caso, la persona debe solicitar visa ante el consulado más cercano y cumplir con los requisitos solicitados; es recomendable acudir directamente al consulado para conocer los requisitos específicos de cada caso. Como referencia general, suelen incluir:' },
        { type: 'ul', items: [
          'Una fotografía tamaño pasaporte',
          'Copia del pasaporte',
          'Certificado de antecedentes judiciales con fines migratorios, apostillado',
          'Itinerario o reservación de vuelo',
          'Comprobante de los medios económicos para cubrir su subsistencia',
          'Pago de los timbres bancarios',
        ] },
        { type: 'p', text: 'La recomendación general es mantener siempre el documento migratorio vigente y actualizado, renovándolo incluso tres meses antes de su vencimiento. Si tu caso involucra un DIMEX vencido o una categoría migratoria específica, agenda una consulta para revisar la mejor ruta según tu situación.' },
      ],
    },
    en: {
      title: 'Expired DIMEX: How to Return to Costa Rica and Renew Your Residency or Refugee Status',
      dek: 'A guide for people who migrated to the United States or another country and need to return to Costa Rica with an expired immigration document (DIMEX).',
      metaDescription: 'How to renew an expired DIMEX and return to Costa Rica after migrating to the United States: which immigration categories can be renewed, which cannot, and what to do in each case.',
      imageAlt: 'Juan Santamaría Airport in Costa Rica',
      body: [
        { type: 'p', text: 'This guide is for migrants who left Costa Rica for the United States — for a variety of reasons, or due to irregular immigration status — and now must or wish to return to the country, as well as for those who stayed in Costa Rica without renewing the documents proving their immigration category.' },
        { type: 'p', text: 'Most Costa Ricans do not emigrate: there are approximately 180,000 Costa Ricans in the United States, while around 230,000 Americans are in Costa Rica, most of them without immigration documents to be in the country. However, some nationals of Nicaragua, Cuba, Venezuela, Haiti, and other countries have migrated to the United States or other destinations after having obtained documents in Costa Rica, such as permanent, temporary, or special-category residency.' },
        { type: 'h2', text: 'Which immigration categories can be renewed in Costa Rica?' },
        { type: 'p', text: 'Two categories can be renewed even after they expire: Permanent Residency and Approved Refugee status (with an approving resolution). Both can be renewed even if the three-month grace period has passed.' },
        { type: 'p', text: 'People with an expired Permanent Residency or Approved Refugee document that has been expired for less than 10 years can renew it through an appointment at 1311, explaining the reasons the renewal was not done, via a note authenticated by an attorney. If the person left the country, they must provide an apostilled criminal record or police record from the country they are returning from.' },
        { type: 'h2', text: 'How do I return to Costa Rica if my DIMEX is expired?' },
        { type: 'p', text: 'It is advisable to request a Certificate of Immigration Status from the General Directorate of Migration and Immigration, via email at certificacionstatus@migracion.go.cr. With that certification and the expired DIMEX, you can demonstrate your right and ability to enter the country to the airline for boarding, and later complete the DIMEX renewal in Costa Rica.' },
        { type: 'h2', text: 'What should I do if I migrated to the United States on humanitarian parole?' },
        { type: 'p', text: 'A common example: a Nicaraguan national with Permanent Residency in Costa Rica, expired for eight years, left legally for the United States under Humanitarian Parole. Before returning to Costa Rica, this person must request a Federal Criminal Record, apostilled in the United States, and arrange their flight, always keeping in mind that the ticket should be purchased with acceptance of the expired DIMEX, or by obtaining a status certification to ensure an orderly return. If more than 10 years have passed without renewal, in addition to the apostilled criminal record, a formal authorization must be requested to determine whether the DIMEX renewal proceeds.' },
        { type: 'h2', text: 'Which immigration categories cannot be renewed?' },
        { type: 'p', text: 'Temporary Residencies expired for more than three months, Special Categories (any) expired for more than three months, and Stay permits expired for more than three months cannot be renewed. It is important to check the wording on the blue or green DIMEX: Temporary Residency, Special Category Free Condition (except Approved Refugee), Special Category Restricted Condition, Digital Nomad Subcategory, or Stay. If these are left expired for more than three months, they are considered lapsed, with no possibility of renewal.' },
        { type: 'h2', text: 'What if my category cannot be renewed?' },
        { type: 'p', text: 'In that case, the person must apply for a visa at the nearest consulate and meet the requested requirements — it is advisable to go directly to the consulate to confirm the specific requirements for each case. As a general reference, these usually include:' },
        { type: 'ul', items: [
          'A passport-size photograph',
          'A copy of the passport',
          'An apostilled judicial background certificate for immigration purposes',
          'A flight itinerary or reservation',
          'Proof of financial means to cover subsistence',
          'Payment of the required bank stamps/fees',
        ] },
        { type: 'p', text: 'The general recommendation is to always keep your immigration document current, renewing it even three months before it expires. If your case involves an expired DIMEX or a specific immigration category, schedule a consultation to review the best path for your situation.' },
      ],
    },
  },
  {
    id: 3,
    slug: { es: 'naturalizacion-solicitantes-refugio-costa-rica', en: 'naturalization-refugee-applicants-costa-rica' },
    image: 'https://confidencial.digital/wp-content/uploads/2025/02/DIMEX.jpg',
    source: {
      url: 'https://confidencial.digital/migrantes/migrantes-noticias/papeles-en-regla/el-derecho-de-los-solicitantes-de-refugio-que-quieren-optar-por-naturalizacion-en-costa-rica/',
      dateEs: '7 de febrero de 2025',
      dateEn: 'February 7, 2025',
    },
    es: {
      title: 'Naturalización para solicitantes de refugio en Costa Rica: qué dice la ley',
      dek: 'A varios solicitantes de refugio les han negado la naturalización en Costa Rica por un criterio equivocado. Esto es lo que establece la normativa vigente.',
      metaDescription: 'Por qué el tiempo como solicitante de refugio sí debe contar para la naturalización en Costa Rica, según el Reglamento 12-2012 y la Sala Constitucional.',
      imageAlt: 'Documento DIMEX de Costa Rica',
      body: [
        { type: 'p', text: 'Es frecuente recibir en consulta a personas a quienes el Registro Civil les negó en primera instancia la naturalización, por supuestamente no cumplir con el tiempo necesario de residencia en Costa Rica para optar a ese proceso. Estas personas eran solicitantes de refugio, y ese tiempo no fue contabilizado dentro de los cinco años que establece la ley. Ese rechazo constituye una vulneración a sus derechos como solicitantes de refugio, por las razones que se explican a continuación.' },
        { type: 'p', text: 'Desde que una persona obtiene su documento de Solicitante de Refugio, regulariza su condición migratoria y accede a un DIMEX, documento que la acompañará en cualquier otra categoría migratoria que llegue a ostentar, cumpliendo así con el reglamento relativo a los trámites, requisitos y criterios de la resolución en materia de naturalizaciones.' },
        { type: 'p', text: 'El Reglamento de esa resolución, número 12-2012, señala en su artículo 8 los requisitos que debe contener el escrito de solicitud, e indica: "Quien solicite la naturalización por residencia deberá presentar un escrito de solicitud que contendrá lo siguiente: d.- Número de documento de identidad. Este documento debe ser el expedido por la Dirección General de Migración y Extranjería en virtud de la concesión de alguna categoría migratoria, o bien, el expedido por el Ministerio de Relaciones Exteriores y Culto, en virtud de la concesión de alguna condición oficial de estancia en el país".' },
        { type: 'h2', text: '¿Qué es el DIMEX en Costa Rica?' },
        { type: 'p', text: 'DIMEX significa Documento de Identidad Migratorio para Extranjeros. Su aplicación en la numeración única de Costa Rica debió iniciar en 1984, pero para las personas extranjeras se ejecutó hasta finales de 2018, cuando se unificaron las bases de datos de Gestión de Extranjería y de la Unidad de Refugio, en cumplimiento del Decreto Ejecutivo 15126, que ordena que todas las instituciones que generen números de identificación integren y operen con números uniformes para las personas físicas.' },
        { type: 'p', text: 'Como parte de ese proceso de unificación de 2018, las personas Solicitantes de Refugio se integraron al Sistema DIMEX, conforme a los artículos 54 y 55 del Reglamento de Personas Refugiadas (Decreto Ejecutivo N.º 36831-G). Por eso, el DIMEX de una persona solicitante de refugio es un carné de color blanco que dice "Carné Provisional Solicitante de Refugio" o "Categoría Especial R" / "Permiso Laboral Categoría Especial R", conforme a la Circular DG-12-02-2023 de la Dirección General de Migración y Extranjería.' },
        { type: 'h2', text: '¿Qué significan los dígitos del DIMEX?' },
        { type: 'p', text: 'El DIMEX de las personas solicitantes de refugio sigue el mismo formato que cualquier otro documento migratorio emitido por la Dirección General de Migración y Extranjería, conforme al Decreto Ejecutivo 15126: un número de doce dígitos para personas extranjeras, que se descompone así:' },
        { type: 'ul', items: [
          'El número 1: indica que la persona es extranjera.',
          'Los siguientes tres dígitos: hacen referencia al país de origen, según el cuadro de códigos de países del sistema WITS (basado en los códigos ISO de 3 letras y los códigos numéricos de la División de Estadística de las Naciones Unidas, UNSD).',
          'Los siguientes seis dígitos: hacen referencia a la cantidad de personas de esa nacionalidad que vivían en Costa Rica a la fecha en que se emitió ese DIMEX.',
          'Los últimos dos dígitos: son el código verificador interno de la Dirección General de Migración y Extranjería.',
        ] },
        { type: 'h2', text: '¿Cuenta el tiempo como solicitante de refugio para la naturalización?' },
        { type: 'p', text: 'La Resolución N.º 17845-2024 de la Sala Constitucional reconoció que a una persona solicitante de refugio se le regulariza de manera temporal su condición migratoria y, en consecuencia, su permanencia en el país se legaliza —es decir, cuenta con residencia oficial en Costa Rica—, aplicándosele las mismas condiciones que a la persona a quien se concedió el estatus de refugiado.' },
        { type: 'p', text: 'Con fundamento en el artículo 9.B.1 del Reglamento relativo a los trámites, requisitos y criterios de resolución en materia de naturalizaciones (N.º 12-2012): "Quien solicite la naturalización por residencia deberá demostrar (…) b.- Haber residido oficialmente en Costa Rica durante los plazos establecidos en el artículo 14 de la Constitución Política (…) b.1.- cinco años para nacionales de otros países de Centroamérica, españoles e iberoamericanos por nacimiento".' },
        { type: 'p', text: 'Y conforme al artículo 11, inciso d) del mismo reglamento: "La residencia oficial en el país se deberá demostrar por medio de la siguiente prueba: (…) d.- La Sección de Opciones y Naturalizaciones solicitará a la Dirección General de Migración y Extranjería una certificación que indique todos los estatus migratorios que ha tenido la parte gestionante hasta la fecha de presentación de la solicitud".' },
        { type: 'p', text: 'Esa certificación de todos los estatus migratorios debe incluir, para no vulnerar los derechos de las personas solicitantes de refugio, el estatus de Solicitud de Refugio: el Registro Civil debe solicitarla, o la persona interesada aportarla, ante la Dirección General de Migración y Extranjería. La Unidad de Refugio es la que otorga el carné de solicitante de refugio (artículo 55 del Reglamento de Refugio) y la que debe certificar el tiempo que la persona estuvo bajo esa condición. Para probarlo, deben aportarse todos los carnés vencidos, certificados notarialmente.' },
        { type: 'p', text: 'Si el Registro Civil te ha negado o cuestionado tu solicitud de naturalización por tu tiempo como solicitante de refugio, este es un tema que conviene revisar con acompañamiento legal. Agenda una consulta para evaluar tu caso.' },
      ],
    },
    en: {
      title: 'Naturalization for Refugee Applicants in Costa Rica: What the Law Says',
      dek: 'Several refugee applicants have been denied naturalization in Costa Rica based on a mistaken criterion. Here is what current regulations actually establish.',
      metaDescription: 'Why time spent as a refugee applicant should count toward naturalization in Costa Rica, according to Regulation 12-2012 and the Constitutional Chamber.',
      imageAlt: 'DIMEX document from Costa Rica',
      body: [
        { type: 'p', text: 'It is common to meet with people whose naturalization application was denied at first instance by the Civil Registry, on the grounds that they supposedly did not meet the required length of residency in Costa Rica. These people were refugee applicants, and that time was not counted toward the five-year period the law establishes. That denial is a violation of their rights as refugee applicants, for the reasons explained below.' },
        { type: 'p', text: 'From the moment a person obtains their Refugee Applicant document, their immigration status is regularized and they gain access to a DIMEX, a document that will accompany them under any other immigration category they later hold, in compliance with the regulation governing the procedures, requirements, and criteria for naturalization resolutions.' },
        { type: 'p', text: 'The Regulation for that resolution, number 12-2012, sets out in article 8 the requirements the application must contain, stating: "Anyone applying for naturalization by residency must submit an application that includes the following: d.- Identity document number. This document must be the one issued by the General Directorate of Migration and Immigration under the granting of an immigration category, or the one issued by the Ministry of Foreign Affairs and Worship under the granting of an official stay condition in the country".' },
        { type: 'h2', text: 'What is the DIMEX in Costa Rica?' },
        { type: 'p', text: 'DIMEX stands for Documento de Identidad Migratorio para Extranjeros (Immigration Identity Document for Foreigners). Its use within Costa Rica’s unified numbering system should have begun in 1984, but for foreign nationals it was not implemented until the end of 2018, when the databases of the Immigration Management office and the Refugee Unit were unified, in compliance with Executive Decree 15126, which orders every institution that issues identification numbers to use uniform numbers for individuals.' },
        { type: 'p', text: 'As part of that 2018 unification process, Refugee Applicants were integrated into the DIMEX System, under articles 54 and 55 of the Refugee Regulations (Executive Decree No. 36831-G). That is why the DIMEX of a refugee applicant is a white card that reads "Provisional Refugee Applicant Card" or "Special Category R" / "Special Category R Work Permit", under Circular DG-12-02-2023 of the General Directorate of Migration and Immigration.' },
        { type: 'h2', text: 'What do the digits on the DIMEX mean?' },
        { type: 'p', text: 'The DIMEX of refugee applicants follows the same format as any other immigration document issued by the General Directorate of Migration and Immigration, under Executive Decree 15126: a twelve-digit number for foreign nationals, broken down as follows:' },
        { type: 'ul', items: [
          'The number 1: indicates the person is a foreign national.',
          'The next three digits: refer to the person’s country of origin, based on the WITS system country code table (built on 3-letter ISO codes and the 3-digit numeric codes from the United Nations Statistics Division, UNSD).',
          'The next six digits: refer to the number of people of that nationality living in Costa Rica at the date that DIMEX was issued.',
          'The last two digits: are the internal verification code of the General Directorate of Migration and Immigration.',
        ] },
        { type: 'h2', text: 'Does time as a refugee applicant count toward naturalization?' },
        { type: 'p', text: 'Constitutional Chamber Resolution No. 17845-2024 recognized that a refugee applicant’s immigration status is temporarily regularized and, as a result, their stay in the country is legalized — meaning they hold official residency in Costa Rica — under the same conditions applied to a person granted refugee status.' },
        { type: 'p', text: 'Based on article 9.B.1 of the Regulation governing the procedures, requirements, and criteria for naturalization resolutions (No. 12-2012): "Anyone applying for naturalization by residency must demonstrate (…) b.- Having officially resided in Costa Rica for the periods established in article 14 of the Political Constitution (…) b.1.- five years for nationals of other Central American countries, Spaniards, and Ibero-Americans by birth".' },
        { type: 'p', text: 'And under article 11, subsection d) of the same regulation: "Official residency in the country must be demonstrated through the following evidence: (…) d.- The Options and Naturalizations Section will request from the General Directorate of Migration and Immigration a certification indicating all the immigration statuses the applicant has held up to the date the application was filed".' },
        { type: 'p', text: 'That certification of all immigration statuses must include, so as not to violate the rights of refugee applicants, the Refugee Applicant status — either requested by the Civil Registry or provided by the applicant, from the General Directorate of Migration and Immigration. The Refugee Unit is the office that issues the refugee applicant card (article 55 of the Refugee Regulations) and the one that must certify the time the person held that status. To prove it, all expired cards, notarially certified, must be submitted.' },
        { type: 'p', text: 'If the Civil Registry has denied or questioned your naturalization application because of your time as a refugee applicant, this is an issue worth reviewing with legal support. Schedule a consultation to evaluate your case.' },
      ],
    },
  },
];

export const getArticleBySlug = (lang, slug) =>
  blogArticles.find((article) => article.slug[lang] === slug);
